### PR TITLE
Use text vs. char field for profile long bio

### LINKED ISSUE #381: Add support for multi-line content in long bios
Multi-line text pasted into the admin form is squashed into a single line. So paragraphs and lists don't work. This should work for submissions from our frontend and via django.

### PR DESCRIPTION
**Pull request by gideonthomas**
Fix #381

To Test - Run migrations and open a profile in the admin and make sure that you see a textarea for long bio in which you can add newlines and that it persists after a save.

### CODE REVIEW

**Comment by Pomax** [comment]
Is this a partial or full fix? Is further work on the client required, or is the client already fine?

**Comment by xmatthewx** [comment]
> Is this a partial or full fix? Is further work on the client required, or is the client already fine?

@mmmavis - any changes required on your end? 

My hope is that all things default to reverse chrono.

**Comment by mmmavis** [comment]
@xmatthewx did you comment on the wrong ticket? 👀

**Comment by xmatthewx** [comment]
> @xmatthewx did you comment on the wrong ticket?

Oopsie doopsie. I'm going to delete the clutter.

**Comment by xmatthewx** [comment]
@Pomax - we don't yet have a client form field to add or update extended profile fields. That's to be added soon. Right now, django is the only way to manage this.

**Comment by gideonthomas** [comment]
ignore the appveyor issue...seems to be platform related.

**Pull request merged**
