### PR TITLE
Switch over auth system to django-allauth and add Github auth

### PR DESCRIPTION
**Pull request by gideonthomas**
This PR adds django-allauth as an auth mechanism and adds Github auth as another way to sign in to pulse.

## TODO
- [x] Fix tests
- [x] Update README
- [x] Change auth routes in pulse front-end to use django-allauth

There's also a small edge case where if you already have an account on pulse with one provider, google/github and you choose to login with the other provider with the same email, it will take you to an ugly sign up page and ask you to login with another email address -- I can fix this in a follow-up issue since it's not critical.

### Setup environment
1. Update your .env file by doing `cp sample.env .env` then add `AUTH_STAFF_EMAIL_DOMAINS=mozillafoundation.org` to the end of the `.env` file.

### Setup Google OAuth (this is already done for staging and prod)
1. Go to https://console.cloud.google.com/projectcreate and create a new project with whatever name.
2. Go to https://console.cloud.google.com/apis/credentials and select your project in the top-left corner.
3. Click on the OAuth Consent Screen tab, fill out an Application Name, add `example.com` to the Authorized Domains and hit the Save button at the bottom.
3. Click on Create Credentials > Oauth Client ID.
4. Select Web Application and give it a name.
5. Add `http://test.example.com:8000` to the Authorized Javascript Domains. Add `http://test.example.com:8000/accounts/google/login/callback/` to Authorized Redirect URLs.
6. Hit Create. Keep this screen open with the Client ID and secret -- you will need it to set it up in the admin.

### Setup Github OAuth
1. Follow the process [here](https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/) to create a Github OAuth app.
2. Set the Homepage URL to `http://test.example.com:8000` and Authorization Callback URL to `http://test.example.com:8000/accounts/github/login/callback/`.
3. Keep the screen with the credentials open -- you will need it to set it up in the admin.

### Add Auth to Django
1. Run `inv migrate` and then create a superuser.
2. Run `inv runserver` and open `http://test.example.com:8000/admin`. Login with your superuser credentials to get into the admin interface.
3. Go to http://test.example.com:8000/admin/socialaccount/socialapp/add/. Select "Google" as the Provider, fill in any name, and fill out the client id and secret from the Google screen you left open. Move `example.com` to the "Chosen Sites" and click "Save and add another".
4. Select "Github" as the Provider and fill out the details like you did for google. Hit Save.
5. Logout of the admin.

### Testing Login flow

There are two states you should start with -- one is a fresh clone of the repo or an empty user database, and the other is with existing prod data (including your login). With prod data, login with google using a user that exists on prod.

Either way, you can choose to use the pulse front-end to test this flow -- I have a branch [here](https://github.com/gideonthomas/network-pulse/tree/test-branch) that automatically calls the allauth routes.

#### Using Pulse API
1. Run `inv runserver` and go to `http://test.example.com:8000`.
2. Click on "Go to Admin website" and it should show you buttons to login via Google or Github or Django Admin. The last option is only shown if the redirect url is to the admin site (so regular pulse users won't see it).
3. Login using your mozillafoundation google account and make sure you're redirected to the admin site correctly. Make sure when you logout of the admin site, you're actually logged out.
4. Repeat these steps for Github as well (use a different email address or an alias mozillafoundation email address so that you don't end up seeing the weird sign up page). If you use a non-mozillafoundation email address, you might see the admin login page with an error saying that you are not authorized to login to the admin page. This is correct behavior.

#### Using Pulse Front-end
1. Run the pulse front-end from my branch and run `inv runserver` in the pulse api.
2. Go to `test.example.com:3000` and click on Sign In.
3. Make sure you're redirected to the login page with options to login using Github or Google only.
4. Login using your mozillafoundation google account and make sure you're redirected to the featured page of pulse front-end correctly.
5. Click on Sign Out and make sure you're redirected to the featured page of pulse front-end correctly and are actually signed out (refresh the page to make sure).
4. Repeat these steps for Github as well (use a different email address or an alias mozillafoundation email address so that you don't end up seeing the weird sign up page).

@alanmoo this doesn't need an in-depth code review, mainly just rigorous testing.

### CODE REVIEW

**Comment by alanmoo** [comment]
Looks like a whole bunch of tests are failing. Feels like maybe I should let you fix that first before spending the time reviewing?

**Comment by gideonthomas** [comment]
@alanmoo most of the tests have to do with faking auth, so it's not related to the actual functionality of this PR, you should be able to review it without the test fixes.

**Comment by alanmoo** [comment]
I'm still investigating/poking at it but one thing I'm seeing is that attempting to log into the pulse-api admin (I haven't touched the front-end repo yet), I get errors when attempting to use a method to log in to an email address that already exists. I'm pretty sure my mofo email address was a google auth'ed account, and attempting to log into it resulted in an error page that the email wasn't unique. 

Additionally, when I deleted the account using my `@gmail.com` superuser django account, attempting to re-login using my mofo email address with Google Auth resulted in the "This user counts as django::staff` box being checked in the admin side (viewed using the superuser account) but no permissions for the mofo account in the admin- is that expected behavior?

**Comment by alanmoo** [comment]
I can't seem to get the client (working from your branch) to recognize that I've logged in to the API. Once it goes through the process the first time, clicking the "signup/signin" link just redirects me to the Pulse homepage, but the link doesn't say my name.

**Comment by alanmoo** [comment]
Also, attempting to log in using Github and this page looks sketchy AF: 
image

**Comment by xmatthewx** [comment]
How's this looking?

**Pull request merged**
