### PR TITLE
Add support for profile response ordering

### PR DESCRIPTION
**Pull request by alanmoo**
And some documentation

### CODE REVIEW

**Comment by mmmavis** [comment]
https://pulse-api.mofostaging.net/api/pulse/profiles/?profile_type=fellow&ordering=name is giving me status `500`. Did I pass the param in the right way? @gideonthomas @alanmoo

**Comment by gideonthomas** [comment]
I don't think drf on its own is equipped to deal with fields like `name` that aren't actual fields on the profiles model. We might have to subclass OrderingFilter and write custom logic to allow ordering by name. Instead, I suggest just doing this in the serializer directly and always order by name instead of allowing you to specify how to order them by via url.

**Comment by alanmoo** [comment]
`custom_name` does work, and a random sampling of our fellows' profiles on production shows they seem to all have custom names. So let's roll with that for now and fix any that are missing it manually.

I'm not sure if the real solution to this is to write a new filter or to straighten out our `custom_name`/`name` situation, but it feels low priority either way. Thoughts @gideonthomas?

**Comment by gideonthomas** [comment]
I'd rather it not 500 at all (so that it doesn't unnecessarily trigger devops paging) so if you're going with that solution, make sure that `ordering_fields` is specified to only allow `custom_name`. That would also mean that we should document that it only allows ordering by `custom_name`.

**Pull request merged**
