### PR TITLE
Stylizing the overall markup structure of the file

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by Pomax** [comment]
Hi @tiagmoraismorgado, can you explain why you filed this PR? Without any comments or explanations, we will not be able to evaluate it in the context of this project.

**Comment by tiagmoraismorgado** [comment]
**with this PR, I do basically aim at:**
- *stylizing the overall structure of the README file*

**in this context i've done the following:**
- *added some bold, and italic sections;*
- *added some separator elements to the overall structure of the file;*

---

**the overall goal of such an edit is:**
- *to improve the overall experience of users on reading the file*

---

**with such an action, i do basically aim at:**
- *re-inforce the overall structure of the file;*
- *making the experience of reading the file better;*
- *making the experience of reading the file easier*

---

**behind such a motivation is the fact that:**
- *people tend to interprete the overall structure of the file, if it is properly highlighted, with styling elements;*

---

**I do, even though, understand it if people have a different opinion on this fact, and think that the styling is not helpful for making the file more readable (i have that opinion as it feels like so to me).**

**My apologies on not having previously including proper referencing and naming to the PR. i know it makes the organization better. so, my honest excuses**

**Comment by tiagmoraismorgado** [comment]
**and i do honestly understand if it's still necessary some work to make my edits to be meaningful for a successful merge. please feel free to draw some comments.**

---

*Kind regards,*
**T.**

**Comment by Pomax** [comment]
That does not quite answer the question: *why* are you filing this PR? There are no issues open around changing the formatting of the file from Markdown to a mix of Markdown and HTML, and you've changed almost all the text from normal text formatting to bold, which is not a good formatting change.

Given that you wish to stylize the overall structure of the README file, you need to say which style guide you're following, because there are no issues to improve the README.md, and the changes you've introduced don't align with any style guide that the Mozilla Foundation follow, so I'm scratching my head about why you filed a PR out of the blue, with changes that don't match any known style formatting. Did someone ask you to file this, was there a request online or in person, etc.?

I'm closing this PR, as it does not address any issue and does not follow any of our style guides, but I would like to know why you sat down to rewrite the README.md because that's time you spent on what you probably felt was helping us improve a project, and while the improvement is not one we can use, understanding why you invested that time will help us direct your efforts that to parts that *can* use help, if you are interested in helping.

**Pull request closed without merging**
