### PR TITLE
adding npm scripts for better dev ergonomics

### PR DESCRIPTION
**Pull request by gvn**
🎉 🎉 🎉

### CODE REVIEW

**Comment by gvn** [comment]
It shouldn't cause any problems...

**Comment by gideonthomas** [comment]
should be fine

**Comment by Pomax** [comment]
One bit problem is that this is unix-specific. We might need to actually write a small script that does a `process.platform` and calls either `source ven/bin/activate` or `venv\Scripts\Activate` depending on the OS found.

**Comment by gvn** [comment]
Let's do that as a follow on since this is just an extra shortcut right now.

**Comment by Pomax** [comment]
but... I'm a windows dev =(

I mean I'm fine with follow-up of course, but it's always that little bit disheartening to see windows getting relegated to an also-ran to be done later. Filed https://github.com/mozilla/network-pulse-api/issues/210 for the follow-up

**Pull request merged**
